branch-defaults:
  master:
    environment: star-wars-dev
environment-defaults:
  star-wars-dev:
    branch: null
    repository: null
global:
  application_name: star-wars
  default_ec2_keyname: aws-eb-swe-keypair
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Python 3.4 running
    on 64bit Amazon Linux/2.3.2
  default_region: us-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
